name: taojuwu
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  azlistview: ^0.1.2
  device_info: ^0.4.2+4
  package_info: ^0.4.1
  shared_preferences: ^0.5.7+1
  # image_picker: ^0.6.4
  flutter_datetime_picker: ^1.3.5
  city_pickers: ^0.1.30
  common_utils: ^1.1.3
  gzx_dropdown_menu: ^1.0.3
  # flutter_splash_screen: ^0.1.0
  # connectivity: any
  extended_image: ^0.9.0
  dio: ^3.0.9
  event_bus: ^1.1.1
  flutter_screenutil: ^1.1.0
  flutter_html: ^0.11.1
  fluro: ^1.6.3
  provider: ^4.0.4
  pull_to_refresh: ^1.5.7
  charts_flutter: ^0.9.0
  barcode_scan: ^3.0.0
  flutter_easyloading: ^1.1.4
  flutter_spinkit: ^4.1.2+1
  # image_picker: ^0.6.6+1
  path_provider: ^1.6.11
  photo_view: ^0.9.2
  syncfusion_flutter_charts: ^18.1.59
  animations: ^1.1.1
  flutter_staggered_animations: ^0.1.2
  install_plugin: ^2.0.1
  flutter_app_upgrade: ^1.1.0
  # barcode_scan:
  #   git:
  #     url: https://github.com/simplezhli/flutter_barcode_reader.git
  # share: ^0.6.3+6
  # fluwx: ^2.0.7
  # tobias: ^1.6.0+1
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/curtain/
    # - locale/i18n_en.json
    - assets/data/province.json
    - assets/data/city.json
    - assets/data/area.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Taojuwu
      fonts:
        - asset: assets/fonts/iconfont.ttf
